#!/bin/bash
set -e

REPO="jkoufopoulos/mailq-prototype"

echo "📋 Creating quality monitor issues on GitHub..."
echo ""


echo "Creating: 🔴 All importance classifications show 0% in statistics but sam..."
curl -s -X POST \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Content-Type: application/json" \
  https://api.github.com/repos/$REPO/issues \
  -d @- << 'ISSUE_JSON' | jq -r '.html_url // .message'
{
  "title": "🔴 [Quality] All importance classifications show 0% in statistics but samples show varied classifications",
  "body": "## Issue Pattern
All importance classifications show 0% in statistics but samples show varied classifications

## Evidence
Overall stats show Critical: 0%, Time-sensitive: 0%, Routine: 0%, but samples contain 3 critical, 10 time-sensitive, and 10 routine emails out of 40 total

## Root Cause
Systematic data inconsistency between aggregation logic and actual classifications - either the stats query is broken or classifications aren't being properly recorded in the summary counts

## Suggested Fix
Debug the statistics aggregation query to ensure it's counting importance levels correctly from the same data source as the samples

---
*Auto-generated by Quality Monitor*
*Severity: high*
*Session: 20251106_022652*
",
  "labels": ["quality", "severity-high", "auto-generated"]
}
ISSUE_JSON

echo ""


echo "Creating: 🔴 Financial statement notifications misclassified as critical..."
curl -s -X POST \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Content-Type: application/json" \
  https://api.github.com/repos/$REPO/issues \
  -d @- << 'ISSUE_JSON' | jq -r '.html_url // .message'
{
  "title": "🔴 [Quality] Financial statement notifications misclassified as critical",
  "body": "## Issue Pattern
Financial statement notifications misclassified as critical

## Evidence
3/3 critical emails are routine financial statements: monthly Green Dot statement (id 12), account eStatement (id 32), and Experian bill deletion notification (id 35)

## Root Cause
Pattern matching on keywords like 'statement is available' and 'your bill' without context - these are automated monthly notifications, not urgent bills requiring immediate action

## Suggested Fix
Distinguish between bill/statement availability notifications (routine) vs. bill due/overdue/payment failed (critical). Add pattern context: 'statement is available/ready' → routine, 'bill due/overdue/payment failed' → critical

---
*Auto-generated by Quality Monitor*
*Severity: high*
*Session: 20251106_022652*
",
  "labels": ["quality", "severity-high", "auto-generated"]
}
ISSUE_JSON

echo ""


echo "Creating: 🔴 Verifier never triggered despite unknown relationships..."
curl -s -X POST \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Content-Type: application/json" \
  https://api.github.com/repos/$REPO/issues \
  -d @- << 'ISSUE_JSON' | jq -r '.html_url // .message'
{
  "title": "🔴 [Quality] Verifier never triggered despite unknown relationships",
  "body": "## Issue Pattern
Verifier never triggered despite unknown relationships

## Evidence
0/40 emails triggered verifier (0.0%), yet all 40 emails show relationship='from_unknown' and decider='unknown'

## Root Cause
Verifier triggering logic appears completely broken - with 100% unknown senders and potentially ambiguous classifications, verifier should be validating at least some classifications

## Suggested Fix
Review verifier triggering conditions. Should trigger for: unknown senders + critical/time-sensitive importance, or when confidence scores are borderline, or when pattern matches are ambiguous

---
*Auto-generated by Quality Monitor*
*Severity: high*
*Session: 20251106_022652*
",
  "labels": ["quality", "severity-high", "auto-generated"]
}
ISSUE_JSON

echo ""


echo "Creating: 🟡 Shipment notifications over-classified as time-sensitive..."
curl -s -X POST \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Content-Type: application/json" \
  https://api.github.com/repos/$REPO/issues \
  -d @- << 'ISSUE_JSON' | jq -r '.html_url // .message'
{
  "title": "🟡 [Quality] Shipment notifications over-classified as time-sensitive",
  "body": "## Issue Pattern
Shipment notifications over-classified as time-sensitive

## Evidence
4/10 time-sensitive emails are shipment updates: 'Shipped' notifications (ids 16, 74) and 'Delivered' notification (id 76). These trigger 'shipment_update' pattern

## Root Cause
All shipment updates treated as time-sensitive, but standard 'shipped' and 'delivered' notifications are informational FYI updates, not requiring immediate attention

## Suggested Fix
Only classify shipment issues as time-sensitive (delayed, failed delivery, requiring signature today). Mark 'shipped' and 'delivered' as routine notifications

---
*Auto-generated by Quality Monitor*
*Severity: medium*
*Session: 20251106_022652*
",
  "labels": ["quality", "severity-medium", "auto-generated"]
}
ISSUE_JSON

echo ""


echo "Creating: 🟡 Policy update misclassified using medical_claims pattern..."
curl -s -X POST \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Content-Type: application/json" \
  https://api.github.com/repos/$REPO/issues \
  -d @- << 'ISSUE_JSON' | jq -r '.html_url // .message'
{
  "title": "🟡 [Quality] Policy update misclassified using medical_claims pattern",
  "body": "## Issue Pattern
Policy update misclassified using medical_claims pattern

## Evidence
Meta privacy policy update (id 30) classified as time-sensitive with reason 'medical_claims (policy)' - this is a social media privacy update, not medical

## Root Cause
Pattern matching 'policy' keyword too broadly without domain context - triggers medical_claims pattern for non-medical policy updates

## Suggested Fix
Require domain context for medical_claims pattern: only trigger if domain includes 'healthcare' or sender is known medical provider. Generic 'policy' updates should be routine

---
*Auto-generated by Quality Monitor*
*Severity: medium*
*Session: 20251106_022652*
",
  "labels": ["quality", "severity-medium", "auto-generated"]
}
ISSUE_JSON

echo ""


echo "Creating: 🟡 Promotional emails with action_required flag elevated to tim..."
curl -s -X POST \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Content-Type: application/json" \
  https://api.github.com/repos/$REPO/issues \
  -d @- << 'ISSUE_JSON' | jq -r '.html_url // .message'
{
  "title": "🟡 [Quality] Promotional emails with action_required flag elevated to time-sensitive",
  "body": "## Issue Pattern
Promotional emails with action_required flag elevated to time-sensitive

## Evidence
2/10 time-sensitive are promotions with action_required: 'Holiday Season Essentials' (id 52) and 'Vote for Lower Fees' (id 60)

## Root Cause
action_required flag doesn't distinguish between genuine required actions (RSVP, form submission deadline) vs. marketing CTAs

## Suggested Fix
Don't auto-elevate to time-sensitive based solely on action_required if email_type is promotion. Require additional signals (deadline, sender relationship) for promotional content

---
*Auto-generated by Quality Monitor*
*Severity: medium*
*Session: 20251106_022652*
",
  "labels": ["quality", "severity-medium", "auto-generated"]
}
ISSUE_JSON

echo ""


echo "Creating: 🟡 All confidence scores are 0.0..."
curl -s -X POST \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Content-Type: application/json" \
  https://api.github.com/repos/$REPO/issues \
  -d @- << 'ISSUE_JSON' | jq -r '.html_url // .message'
{
  "title": "🟡 [Quality] All confidence scores are 0.0",
  "body": "## Issue Pattern
All confidence scores are 0.0

## Evidence
All 40 emails show type_confidence: 0.0, all domain_confidence fields are empty objects {}

## Root Cause
Confidence scoring system not implemented or not being populated - makes it impossible to identify low-confidence classifications that need review

## Suggested Fix
Implement confidence scoring based on pattern match strength, sender recognition, and classification certainty. Use confidence thresholds to trigger verifier

---
*Auto-generated by Quality Monitor*
*Severity: medium*
*Session: 20251106_022652*
",
  "labels": ["quality", "severity-medium", "auto-generated"]
}
ISSUE_JSON

echo ""


echo "Creating: 🟡 Low entity extraction rate..."
curl -s -X POST \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Content-Type: application/json" \
  https://api.github.com/repos/$REPO/issues \
  -d @- << 'ISSUE_JSON' | jq -r '.html_url // .message'
{
  "title": "🟡 [Quality] Low entity extraction rate",
  "body": "## Issue Pattern
Low entity extraction rate

## Evidence
Only 15/40 emails (37.5%) have entities extracted. All routine emails (10/10) have no entities. Most extracted entities are generic 'notification' type (low value)

## Root Cause
Entity extraction appears to only trigger for non-routine emails, missing opportunities to extract useful structured data (merchants, amounts, dates) from receipts and other routine mail

## Suggested Fix
Extract entities from all email types, especially receipts (merchant, amount, items), events (date, time, location), and bills (amount due, due date). Current 'notification' entity type is too generic to be useful

---
*Auto-generated by Quality Monitor*
*Severity: medium*
*Session: 20251106_022652*
",
  "labels": ["quality", "severity-medium", "auto-generated"]
}
ISSUE_JSON

echo ""


echo "Creating: ⚪ Generic all-event time-sensitive classification..."
curl -s -X POST \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Content-Type: application/json" \
  https://api.github.com/repos/$REPO/issues \
  -d @- << 'ISSUE_JSON' | jq -r '.html_url // .message'
{
  "title": "⚪ [Quality] Generic all-event time-sensitive classification",
  "body": "## Issue Pattern
Generic all-event time-sensitive classification

## Evidence
2/10 time-sensitive emails classified solely because email_type='event' without checking timing: 'CHAW Open Drawing - November 7' (id 84) has reason 'email type: event'

## Root Cause
Blanket rule that all events are time-sensitive, but events far in future or past events don't require immediate attention

## Suggested Fix
Parse event dates and only mark as time-sensitive if event is within 7 days. Events beyond that should be routine unless they have explicit urgency signals

---
*Auto-generated by Quality Monitor*
*Severity: low*
*Session: 20251106_022652*
",
  "labels": ["quality", "severity-low", "auto-generated"]
}
ISSUE_JSON

echo ""


echo "Creating: ⚪ Empty from_email field for all emails..."
curl -s -X POST \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Content-Type: application/json" \
  https://api.github.com/repos/$REPO/issues \
  -d @- << 'ISSUE_JSON' | jq -r '.html_url // .message'
{
  "title": "⚪ [Quality] Empty from_email field for all emails",
  "body": "## Issue Pattern
Empty from_email field for all emails

## Evidence
All 40 emails show from_email: '' (empty string), yet relationships are classified as 'from_unknown'

## Root Cause
Email sender extraction not working or not being populated - prevents sender-based classification rules and relationship analysis

## Suggested Fix
Fix sender email extraction in email processing pipeline. Use sender domain and email to improve classification accuracy and build sender reputation

---
*Auto-generated by Quality Monitor*
*Severity: low*
*Session: 20251106_022652*
",
  "labels": ["quality", "severity-low", "auto-generated"]
}
ISSUE_JSON

echo ""


echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ All quality monitor issues created!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
