#!/usr/bin/env python3
"""
Create GitHub issues for unresolved quality problems
"""

from __future__ import annotations

import json
import os
import sqlite3
import sys
import urllib.request
from pathlib import Path

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
GITHUB_REPO = "jkoufopoulos/mailq-prototype"
DB_PATH = Path(__file__).parent / "quality_monitor.db"

SEVERITY_EMOJI = {"high": "🔴", "medium": "🟡", "low": "⚪"}


def create_github_issue(issue):
    """Create a GitHub issue"""
    emoji = SEVERITY_EMOJI.get(issue["severity"], "⚪")

    title = f"{emoji} [Quality] {issue['pattern']}"

    body = f"""## Issue Pattern
{issue["pattern"]}

## Evidence
{issue["evidence"]}

## Root Cause
{issue["root_cause"]}

## Suggested Fix
{issue["suggested_fix"]}

---
*Auto-generated by Quality Monitor*
*Severity: {issue["severity"]}*
"""

    data = json.dumps(
        {
            "title": title,
            "body": body,
            "labels": ["quality", f"severity-{issue['severity']}", "auto-generated"],
        }
    ).encode()

    req = urllib.request.Request(
        f"https://api.github.com/repos/{GITHUB_REPO}/issues",
        data=data,
        headers={
            "Authorization": f"Bearer {GITHUB_TOKEN}",
            "Accept": "application/vnd.github.v3+json",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=10) as response:
            result = json.loads(response.read().decode())
            return result.get("html_url"), result.get("number")
    except Exception as e:
        print(f"❌ Failed to create issue: {e}")
        return None, None


def main():
    # Validate GitHub token is set
    if not GITHUB_TOKEN:
        print("❌ ERROR: GITHUB_TOKEN environment variable not set", file=sys.stderr)
        print("   Please set GITHUB_TOKEN to your GitHub personal access token", file=sys.stderr)
        print("   Example: export GITHUB_TOKEN=ghp_xxxxxxxxxxxxx", file=sys.stderr)
        sys.exit(1)

    # Get unresolved issues from database
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    cursor.execute("""
        SELECT id, severity, pattern, evidence, root_cause, suggested_fix
        FROM quality_issues
        WHERE resolved=0
        ORDER BY CASE severity
            WHEN 'high' THEN 1
            WHEN 'medium' THEN 2
            WHEN 'low' THEN 3
        END, created_at DESC
    """)

    issues = []
    for row in cursor.fetchall():
        issues.append(
            {
                "id": row[0],
                "severity": row[1],
                "pattern": row[2],
                "evidence": row[3],
                "root_cause": row[4],
                "suggested_fix": row[5],
            }
        )

    print(f"Found {len(issues)} unresolved issues\n")

    # Create GitHub issues (only for medium+ severity per existing logic)
    created_issues = []

    for issue in issues:
        emoji = SEVERITY_EMOJI.get(issue["severity"], "⚪")
        print(f"Creating: {emoji} {issue['pattern'][:60]}...")

        # Only create for medium+ severity
        if issue["severity"] in ["high", "medium"]:
            url, number = create_github_issue(issue)
            if url:
                print(f"  ✅ Created: {url}\n")

                # Update database with GitHub URL
                cursor.execute(
                    """
                    UPDATE quality_issues
                    SET github_issue_url = ?
                    WHERE id = ?
                """,
                    (url, issue["id"]),
                )

                created_issues.append(
                    {
                        "number": number,
                        "url": url,
                        "pattern": issue["pattern"],
                        "severity": issue["severity"],
                    }
                )
            else:
                print("  ❌ Failed to create\n")
        else:
            print("  ⏭️  Skipped (low severity - no GitHub issue per policy)\n")

    conn.commit()
    conn.close()

    print("\n" + "=" * 80)
    print("SUMMARY")
    print("=" * 80)
    print(f"\nCreated {len(created_issues)} GitHub issues:\n")

    for item in created_issues:
        emoji = SEVERITY_EMOJI.get(item["severity"], "⚪")
        print(f"{emoji} #{item['number']}: {item['pattern']}")
        print(f"   {item['url']}\n")


if __name__ == "__main__":
    main()
